<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>

    <TargetFramework>net10.0</TargetFramework>

    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <!-- Publication autonome et Single File -->
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>

    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>

    <!-- Icône Windows -->
    <ApplicationIcon Condition="'$(RuntimeIdentifier)' == 'win-x64'">Assets\PTN.ico</ApplicationIcon>

    <!-- AppHost nécessaire pour les applications natives -->
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
    <OutputType>Exe</OutputType>
    <AssemblyName>PTN</AssemblyName>
    <ApplicationTitle>Pas l'Temps d'Niaiser !</ApplicationTitle>
    <ApplicationVersion>1.0.0</ApplicationVersion>
    <RuntimeIdentifier>osx-x64</RuntimeIdentifier>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
    <OutputType>Exe</OutputType>
    <AssemblyName>PTN</AssemblyName>
    <ApplicationTitle>Pas l'Temps d'Niaiser !</ApplicationTitle>
    <ApplicationVersion>1.0.0</ApplicationVersion>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.9" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />

    <PackageReference Include="Tmds.DBus.Protocol" Version="0.21.3" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

</Project>